# Students Do: Predicting Loan Default with Random Forests

In this activity, you are going to explore how random forest algorithm can be used to identify loans that are likely to default. You will use the `sba_loans_encoded.csv` file that you created before to train the model

In [1]:
# Initial imports
import pandas as pd
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

## Loading and Preprocessing Loans Encoded Data

Load the `sba_loans_encoded.csv` in a pandas DataFrame called `df_loans`

In [3]:
# Loading data
df_loans = pd.read_csv("../Resources/sba_loans_encoded.csv")
df_loans

,Year,Month,Amount,Term,Zip,CreateJob,NoEmp,RealEstate,RevLineCr,UrbanRural,...,City_WILLITS,City_WILMINGTON,City_WINDSOR,City_WINNETKA,City_WOODLAND,City_WOODLAND HILLS,City_WRIGHTWOOD,City_Watsonville,City_YORBA LINDA,City_YUBA CITY
0,2001,11,32812,36,92801,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2001,4,30000,56,90505,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2001,4,30000,36,92103,0,10,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2003,10,50000,36,92108,0,6,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2006,7,343000,240,91345,3,65,1,0,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,2006,6,150000,60,92346,0,5,0,0,2,...,0,0,0,0,0,0,0,0,0,0
2093,1997,4,99000,300,92021,0,4,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2094,1997,2,50000,84,93012,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2095,1997,1,251150,120,91352,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2096,1997,7,35000,60,90068,0,4,0,1,0,...,0,0,0,0,0,0,0,0,0,0

Define the features set, by copying the `df_loans` DataFrame and dropping the `Default` column.

In [7]:
# Define features set
x = df_loans.copy()
x = x.drop(columns="Default")

x

,Year,Month,Amount,Term,Zip,CreateJob,NoEmp,RealEstate,RevLineCr,UrbanRural,...,City_WILLITS,City_WILMINGTON,City_WINDSOR,City_WINNETKA,City_WOODLAND,City_WOODLAND HILLS,City_WRIGHTWOOD,City_Watsonville,City_YORBA LINDA,City_YUBA CITY
0,2001,11,32812,36,92801,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,2001,4,30000,56,90505,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2001,4,30000,36,92103,0,10,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,2003,10,50000,36,92108,0,6,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2006,7,343000,240,91345,3,65,1,0,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092,2006,6,150000,60,92346,0,5,0,0,2,...,0,0,0,0,0,0,0,0,0,0
2093,1997,4,99000,300,92021,0,4,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2094,1997,2,50000,84,93012,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2095,1997,1,251150,120,91352,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2096,1997,7,35000,60,90068,0,4,0,1,0,...,0,0,0,0,0,0,0,0,0,0

Create the target vector by assigning the values of the `Default` column from the `df_loans` DataFrame.

In [9]:
# Define target vector

y = df_loans["Default"].values.reshape(-1,1)

y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

Split the data into training and testing sets.

In [10]:
# Splitting into Train and Test sets

x_test, x_train, y_test, y_train = train_test_split(x,y,random_state=78)

Use the `StandardScaler` to scale the features data, remember that only `X_train` and `X_testing` DataFrames should be scaled.

In [11]:
# Create the StandardScaler instance
ss = StandardScaler()

In [12]:
# Fit the Standard Scaler with the training data

x_scaler = ss.fit(x_train)

In [13]:
# Scale the training data

x_test_scaled = x_scaler.transform(x_test)

x_train_scaled = x_scaler.transform(x_train)

## Fitting the Random Forest Model

Once data is scaled, create a random forest instance and train it with the training data (`X_train_scaled` and `y_train`), define `n_estimators=500` and `random_state=78`.

In [14]:
# Create the random forest classifier instance

rf_model = RandomForestClassifier(n_estimators=500, random_state=78)

In [15]:
# Fit the model

rf_model = rf_model.fit(x_train_scaled, y_train)

/Users/hakobkeymetlyan/opt/anaconda3/envs/dev/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

## Making Predictions Using the Random Forest Model

Validate the trained model, by predicting loan defaults using the testing data (`X_test_scaled`).

In [16]:
# Making predictions using the testing data

predictions = rf_model.predict(x_test_scaled)

## Model Evaluation

Evaluate model's results, by using `sklearn` to calculate the confusion matrix, the accuracy score and to generate the classification report.

In [17]:
# Calculating the confusion matrix
cm = confusion_matrix(y_test, predictions)

cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)
# Calculating the accuracy score

acc_score = accuracy_score(y_test, predictions)

In [18]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0          988           79
Actual 1           81          424

Accuracy Score : 0.8982188295165394
Classification Report
              precision    recall  f1-score   support

           0       0.92      0.93      0.93      1067
           1       0.84      0.84      0.84       505

    accuracy                           0.90      1572
   macro avg       0.88      0.88      0.88      1572
weighted avg       0.90      0.90      0.90      1572

## Feature Importance

In this section, you are asked to fetch the features' importance from the random forest model and display the top 10 most important features.

In [19]:
# Get the feature importance array
importances = rf_model.feature_importances_

In [24]:
# List the top 10 most important features

importance_sorted = sorted(zip(rf_model.feature_importances_, x.columns), reverse=True)
importance_sorted

[(0.26364099604720953, 'Term'),
 (0.08351281823786369, 'Year'),
 (0.08330403703338427, 'Amount'),
 (0.05025563647685759, 'Zip'),
 (0.03951469954001163, 'NoEmp'),
 (0.03863888534729672, 'Month'),
 (0.03676387828231279, 'RealEstate'),
 (0.03465420177816074, 'RevLineCr'),
 (0.02493945963174351, 'CreateJob'),
 (0.019465553140959494, 'Bank_BANK OF AMERICA NATL ASSOC'),
 (0.013773859539404996, 'UrbanRural'),
 (0.010222365678964507, 'Bank_BBCN BANK'),
 (0.0064555808800925525, 'Bank_WELLS FARGO BANK NATL ASSOC'),
 (0.006412532940785636, 'Bank_CAPITAL ONE NATL ASSOC'),
 (0.006228986181480801, 'Bank_U.S. BANK NATIONAL ASSOCIATION'),
 (0.006002085106749823, 'City_SAN DIEGO'),
 (0.00585479109151305, 'Bank_CITIBANK, N.A.'),
 (0.005733506962154835, 'Bank_JPMORGAN CHASE BANK NATL ASSOC'),
 (0.005125310304157387, 'City_HERCULES'),
 (0.005024061445096221, 'Bank_SUPERIOR FINANCIAL GROUP, LLC'),
 (0.004856360219994621, 'City_LOS ANGELES'),
 (0.004452247676737376, 'Bank_CDC SMALL BUS. FINAN CORP'),
 (0.00431805911817992, 'City_SAN JOSE'),
 (0.004167162006532822, 'Bank_UMPQUA BANK'),
 (0.004076641745202732, 'City_SALINAS'),
 (0.003401052689925936, 'City_TORRANCE'),
 (0.0032463653678189578, 'Bank_CALIFORNIA BANK & TRUST'),
 (0.0032283692455853377, 'City_FOLSOM'),
 (0.0030318387684247425, 'Bank_PACIFIC WESTERN BANK'),
 (0.002994324541492583, 'City_NEWARK'),
 (0.0029267830761578392, 'City_SACRAMENTO'),
 (0.0028438398471929407, 'City_GRANADA HILLS'),
 (0.0028340795878572206, 'City_CHULA VISTA'),
 (0.0028025949427375415, 'City_SAN FRANCISCO'),
 (0.002679918067351429, 'City_OAKLAND'),
 (0.002578159266904493, 'Bank_MUFG UNION BANK NATL ASSOC'),
 (0.002545879663785209, 'City_ANAHEIM'),
 (0.0024916977006231847, 'City_RIVERSIDE'),
 (0.0024206505762919147, 'Bank_TRI COUNTIES BANK'),
 (0.0024056085813981237, 'Bank_CENTRAL VALLEY COMMUNITY BANK'),
 (0.002359653997012907, 'Bank_WESTERN ALLIANCE BANK'),
 (0.002340299692287492, 'Bank_COMERICA BANK'),
 (0.0022929168368617486, 'City_HUNTINGTON PARK'),
 (0.0022433743361218034, 'Bank_BANCO POPULAR NORTH AMERICA'),
 (0.0022193589592436566, 'City_VALENCIA'),
 (0.0021865649455642066, 'City_BAKERSFIELD'),
 (0.0021285596611767274, 'City_HUNTINGTON BEACH'),
 (0.002103996436322322, 'City_SAN PEDRO'),
 (0.0020410869378765886, 'City_CAMARILLO'),
 (0.002006891560282581, 'Bank_AURORA BANK FSB'),
 (0.002002532183725058, 'City_LOS GATOS'),
 (0.0019643356641284382, 'City_SAN DIMAS'),
 (0.0019145696040190634, 'City_ATWATER'),
 (0.0019024933755042127, 'Bank_WESTAMERICA BANK'),
 (0.0018976105451579562, 'Bank_SEACOAST COMMERCE BANK'),
 (0.0018756027721204983, 'Bank_WILSHIRE BANK'),
 (0.0018611925479958768, 'City_SAN MARCOS'),
 (0.001860167760352936, 'City_LAGUNA HILLS'),
 (0.001832554825562634, 'City_IRVINE'),
 (0.001816271309409679, 'Bank_BENEFICIAL STATE BANK'),
 (0.0017961361114044612, 'City_SANTA ANA'),
 (0.0017571676500961323, 'City_GLENDALE'),
 (0.0017259430490502656, 'Bank_MISSION NATIONAL BANK'),
 (0.0017024529442672767, 'Bank_HANMI BANK'),
 (0.0017007095839536295, 'City_TRUCKEE'),
 (0.0016939291251145364, 'City_CHATSWORTH'),
 (0.0016762326529692975, 'City_Chula Vista'),
 (0.001673780103705982, 'City_EL CAJON'),
 (0.0016560754999078169, 'City_NEWPORT BEACH'),
 (0.001648989284032214, 'Bank_COMMUNITY W. BANK NATL ASSOC'),
 (0.001547654062436697, 'City_BURBANK'),
 (0.0015127061737967267, 'City_FREMONT'),
 (0.0014623449168799946, 'City_VISALIA'),
 (0.0014469592458955021, 'Bank_SECURITY BANK OF CALIFORNIA'),
 (0.0014437380976728175, 'Bank_SANTA CLARA VALLEY BANK NATL A'),
 (0.001438876437023869, 'City_DANVILLE'),
 (0.0014360384351929036, 'City_WINNETKA'),
 (0.0014353489945151058, 'City_MISSION VIEJO'),
 (0.0013944503207442788, 'Bank_SHINHAN BANK AMERICA'),
 (0.0013780539836054893, 'Bank_COAST NATIONAL BANK'),
 (0.0013661890202160563, 'City_MURRIETA'),
 (0.0013580958240236027, 'City_LA MESA'),
 (0.0013407485047977454, 'City_YUBA CITY'),
 (0.0013325384563187834, 'Bank_LOGIX FCU'),
 (0.0013097148295159982, 'City_Granada Hills'),
 (0.0013032027172552201, 'Bank_UNITI BANK'),
 (0.0012878139297073437, 'City_San Bernardino'),
 (0.001282169342907078, 'City_GARDENA'),
 (0.0012620803059448721, 'City_PASADENA'),
 (0.0012541827459716453, 'City_ROSEVILLE'),
 (0.001244308160394202, 'City_LIVERMORE'),
 (0.0011962989428810538, 'Bank_MISSION VALLEY BANK'),
 (0.0011912148246479178, 'City_CUPERTINO'),
 (0.0011757294454342354, 'City_NORTH HOLLYWOOD'),
 (0.0011751300676491204, 'City_San Luis Obispo'),
 (0.0011683318195441566, 'City_GROVER BEACH'),
 (0.001130064644775809, 'Bank_MORTGAGE CAP. DEVEL CORP'),
 (0.0011195874328017547, 'City_WOODLAND HILLS'),
 (0.001112552783222315, 'City_BERKELEY'),
 (0.0011111117405956878, 'City_Berkeley'),
 (0.0010987166929226047, 'City_SAN LUIS OBISPO'),
 (0.0010919423178117312, 'City_RANCHO MIRAGE'),
 (0.0010889353470270753, 'City_BEVERLY HILLS'),
 (0.0010819087443342923, 'City_CITY OF INDUSTRY (INDUSTRY)'),
 (0.0010810774553232708, 'City_COMPTON'),
 (0.0010769609120197532, 'City_MODESTO'),
 (0.0010622220594311766, 'City_HAWTHORNE'),
 (0.0010592355464141615, 'City_PALMDALE'),
 (0.0010499897809613397, 'City_SOUTH SAN FRANCISCO'),
 (0.0010489767929570727, 'City_BENICIA'),
 (0.0010464604101661252, 'City_HIGHLAND'),
 (0.0010451728719471068, 'City_LONG BEACH'),
 (0.0010445790299744282, 'Bank_ONEWEST BANK NATL ASSOC'),
 (0.001029462350085473, 'Bank_DESERT COMMUN BANK A DIVISION'),
 (0.00100754874723076, 'Bank_SBA - EDF ENFORCEMENT ACTION'),
 (0.0010068341522336645, 'City_TEMECULA'),
 (0.0009947808636952867, 'Bank_BANK OF AMERICA CALIFORNIA N.A'),
 (0.0009869910140433951, 'City_SUNNYVALE'),
 (0.0009743591025922995, 'City_SAN BERNARDINO'),
 (0.0009715608713296557, 'City_SUISUN CITY'),
 (0.000969076582696385, 'City_MECCA'),
 (0.0009614119324032975, 'City_ENCINITAS'),
 (0.0009586677952076483, 'City_STOCKTON'),
 (0.000933785632993302, 'Bank_AMERICAN CONTINENTAL BANK'),
 (0.0009042077793655212, 'City_Fairfield'),
 (0.0009034504341673199, 'City_San clemente'),
 (0.0008933241378964504, 'City_SANTA CLARA'),
 (0.0008876670074507704, 'City_CARSON'),
 (0.0008520981872118981, 'City_ELK GROVE'),
 (0.0008502355649915368, 'City_SAN MATEO'),
 (0.000840111204322479, 'City_BARSTOW'),
 (0.0008318107164152315, 'City_NORCO'),
 (0.0008303670904586555, 'City_CARLSBAD'),
 (0.0008265685954658335, 'City_SUN VILLAGE'),
 (0.0008225431784980603, 'City_CORONA'),
 (0.0008183632505140586, 'City_VENTURA (CORPORATE NAME SAN BU'),
 (0.000808831002513181, 'City_HOLLISTER'),
 (0.000793705006531522, 'Bank_FOUNDERS COMMUNITY BANK'),
 (0.0007765497117307461, 'City_OAKDALE'),
 (0.0007690910131320128, 'Bank_EAST WEST BANK'),
 (0.0007666648670772256, 'City_COSTA MESA'),
 (0.0007644915778256448, 'City_FRESNO'),
 (0.0007584774643333117, 'City_SAN RAFAEL'),
 (0.0007534491639298213, 'City_VACAVILLE'),
 (0.000750743168760236, 'City_WEST HILLS'),
 (0.000741648228536636, 'Bank_HERITAGE OAKS BANK'),
 (0.0007272777713330436, 'City_AGOURA HILLS'),
 (0.0007203520053697052, 'City_SAN CLEMENTE'),
 (0.0006974661883948616, 'City_NEWHALL'),
 (0.0006886839562091885, 'City_Los Angeles'),
 (0.0006743406623155399, 'City_SANTA ROSA'),
 (0.0006739640756620528, 'City_SAN GABRIEL'),
 (0.0006659701988469944, 'City_CULVER CITY'),
 (0.0006646833373941295, 'City_Hayward'),
 (0.000643800009630893, 'City_CALIENTE'),
 (0.0006191264648910938, 'City_IDYLLWILD'),
 (0.0006113713108381844, 'City_DIAMOND BAR'),
 (0.0006106974714331588, 'City_WILDOMAR'),
 (0.0005961471555115281, 'City_BYRON'),
 (0.000592459656557546, 'Bank_MECHANICS BANK'),
 (0.0005808040898085695, 'City_WEST COVINA'),
 (0.0005758085699894162, 'City_INGLEWOOD'),
 (0.0005578211075018401, 'City_TULARE'),
 (0.0005556245977156548, 'City_CERRITOS (DAIRY VALLEY)'),
 (0.0005456058358550887, 'Bank_CITIZENS BANK NATL ASSOC'),
 (0.0005446255785669401, 'City_SANTA BARBARA'),
 (0.0005433121790222525, 'City_El Cajon'),
 (0.0005423062068775312, 'Bank_FREMONT BANK'),
 (0.0005421654295543395, 'City_PACIFICA'),
 (0.0005381811918843905, 'City_ACTON'),
 (0.0005380017176137653, 'City_LA QUINTA'),
 (0.0005227021982150241, 'City_WALNUT'),
 (0.0005176436915234989, 'Bank_FARMERS & MERCHANTS BK OF CENT'),
 (0.0005109125622161416, 'City_VAN NUYS'),
 (0.0005044903725363588, 'City_WEST HOLLYWOOD'),
 (0.000502513559271585, 'City_BREA'),
 (0.0004930118458710734, 'City_ALTADENA'),
 (0.0004907197760624381, 'City_PETALUMA'),
 (0.0004879426594073352, 'City_WHITTIER'),
 (0.00048066391339310436, 'City_NORWALK'),
 (0.00048003161671424625, 'City_AGUANGA'),
 (0.00047958516868742843, 'City_FULLERTON'),
 (0.00047682070176748964, 'City_SANTA MONICA'),
 (0.0004694631409880554, 'City_DEL MAR'),
 (0.00046912466418285516, 'City_LAKESHORE'),
 (0.00046746019016149744, 'City_MORGAN HILL (MORGANHILL)'),
 (0.00046521338426087623, 'City_SOUTH PASADENA'),
 (0.00046361394997221627, 'City_STANTON'),
 (0.0004593210722027656, 'City_ANTIOCH'),
 (0.00045831321389858495, 'City_BRENTWOOD'),
 (0.0004574031855607377, 'City_FOUNTAIN VALLEY'),
 (0.00043637870239536677, 'City_LAGUNA BEACH'),
 (0.0004297599198312621, 'City_HAWAIIAN GARDENS'),
 (0.0004290751039166146, 'Bank_CAPITAL ONE BK (USA) NATL ASSO'),
 (0.0004229257287838189, 'City_DOWNEY'),
 (0.0004216123744355324, 'City_VALLEJO'),
 (0.00042027313060889537, 'City_SAN RAMON'),
 (0.00041882686741297073, 'City_SIMI VALLEY (SIMI)'),
 (0.0004104527570082701, 'City_WOODLAND'),
 (0.00040962376578103295, 'City_PINOLE'),
 (0.0004094831368138962, 'City_LANCASTER'),
 (0.00040476136030923764, 'City_Stanton'),
 (0.0004029606293890356, 'City_DUBLIN'),
 (0.0003994008308112035, 'City_SANTA PAULA'),
 (0.00039841576378244435, 'City_STUDIO CITY'),
 (0.00038885531429669405, 'City_ISLETON'),
 (0.0003886507106234961, 'City_HILMAR'),
 (0.0003858709032753292, 'Bank_GE CAP. SMALL BUS. FINAN CORP'),
 (0.000380489357102016, 'City_HESPERIA'),
 (0.0003785348066263921, 'City_FRAZIER PARK'),
 (0.00037556419394373726, 'City_San Francisco'),
 (0.00036072587632743987, 'Bank_PACIFIC ENTERPRISE BANK'),
 (0.0003604059744567491, 'City_BETHEL ISLAND'),
 (0.00036007920254391146, 'City_LINCOLN'),
 (0.00035734907873119796, 'City_WEST HOLLYWOOD (BR. P.O. NAME'),
 (0.00035630698194163225, 'City_RANCHO SANTA MARGARITA'),
 (0.0003559808372053635, 'City_UNION CITY'),
 (0.0003537216594948848, 'City_UPLAND'),
 (0.0003491756226802741, 'Bank_FIRST CALIFORNIA BANK'),
 (0.00034906861897519555, 'City_MONTEBELLO'),
 (0.0003461123350602812, 'City_PANORAMA CITY'),
 (0.00034395036376204483, 'Bank_CALIFORNIA STATEWIDE CERT. DEV'),
 (0.0003269533604679072, 'City_BUENA PARK'),
 (0.00032077653290738146, 'City_RCH CUCAMONGA'),
 (0.0003172524055195953, 'City_LA JOLLA'),
 (0.00031099639915739216, 'Bank_FIRST NATL BK OF NORTHERN CALI'),
 (0.0003095827214291152, 'City_PICO RIVERA'),
 (0.00030705783968969236, 'City_EXETER'),
 (0.00029713842923871495, 'City_NEVADA CITY'),
 (0.00029502621890593997, 'City_PLEASANTON'),
 (0.00029221572133028274, 'City_TRACY'),
 (0.0002896014318979692, 'City_ONTARIO'),
 (0.0002892246432972254, 'City_LA PUENTE'),
 (0.00027629050916837315, 'City_CHOWCHILLA'),
 (0.00027338060800982504, 'City_TARZANA'),
 (0.0002726122916232476, 'Bank_COMMUNITY BANK'),
 (0.00026011866450517137, 'Bank_WACHOVIA SBA LENDING, INC.'),
 (0.00025393634637303606, 'Bank_BANC OF CALIFORNIA NATL ASSOC'),
 (0.00024603222031464606, 'City_Quincy'),
 (0.00024019151871054688, 'Bank_FIRST-CITIZENS BK & TR CO'),
 (0.00023580697303241668, 'Bank_NATIONAL BANK OF CALIFORNIA'),
 (0.00022261814868250582, 'Bank_BUSINESS LOAN CENTER, LLC'),
 (0.00021583692558371412, 'City_COLTON'),
 (0.0002119332111643097, 'Bank_MUTUAL OF OMAHA BANK'),
 (0.00020876685761727308, 'Bank_NORTH VALLEY BANK'),
 (0.000202720293089837, 'Bank_INNOVATIVE BANK'),
 (0.0001955468355844189, 'City_ROSEMEAD'),
 (0.00019423707693205742, 'City_SUN VALLEY'),
 (0.0001874478114299282, 'City_FAIR OAKS'),
 (0.00018435711953253742, 'City_ORANGEVALE'),
 (0.00018263441874684204, 'City_PLACERVILLE'),
 (0.0001772298401325297, 'Bank_CAPITAL ACCESS GROUP, INC.'),
 (0.00017079263501696042, 'City_Burbank'),
 (0.00016972833796637481, 'City_YORBA LINDA'),
 (0.00016737336251927842, 'City_GARDEN GROVE'),
 (0.00015928695181414428, 'City_PALM DESERT'),
 (0.0001524474811746117, 'City_CAMERON PARK'),
 (0.00014821587296887106, 'City_PASO ROBLES (CORPORATE NAME EL'),
 (0.00014741735106679665, 'City_BURLINGAME'),
 (0.00013834219167710088, 'Bank_CALIFORNIA UNITED BANK'),
 (0.0001373915611466964, 'Bank_FIRST PRIVATE BANK & TRUST'),
 (0.00013497695558542964, 'City_VENTURA'),
 (0.00013207019763278348, 'City_OCEANSIDE'),
 (0.0001285766615401498, 'Bank_LOANS FROM OLD CLOSED LENDERS'),
 (0.000123922147005925, 'City_Garden grove'),
 (0.00012182095526179453, 'City_PERRIS'),
 (0.00011988156396219328, 'Bank_GREATER SACRAMENTO CERT. DEVEL'),
 (0.0001198674885168041, 'Bank_PLAZA BANK'),
 (0.0001164073518522645, 'Bank_EH NATIONAL BANK'),
 (0.00011527741577838221, 'City_BELLFLOWER'),
 (0.0001136827499709674, 'City_FAIRFIELD'),
 (0.00011356194125844908, 'City_DALY CITY'),
 (0.00011174374631880778, 'City_CHINO'),
 (0.00010738975308002978, 'City_ALPINE'),
 (0.00010475819634911405, 'City_TEHACHAPI'),
 (0.00010130692859929205, 'Bank_ADVANTAGE CERT. DEVEL CORP'),
 (9.966259514678252e-05, 'Bank_UNION BANK, N.A.'),
 (9.85350031316356e-05, 'Bank_SOUTHLAND ECONOMIC DEVEL CORP'),
 (9.775597258364981e-05, 'Bank_MONTEREY COUNTY BANK'),
 (9.57746399061078e-05, 'City_PACOIMA'),
 (9.54654141578773e-05, 'Bank_CITIZENS BUSINESS BANK'),
 (9.232563998568171e-05, 'Bank_GOVERMNET FUNDING CALBIDCO'),
 (8.988001993176041e-05, 'City_FORT BRAGG'),
 (8.782882132489555e-05, 'Bank_FIRST BANK'),
 (8.782599322472158e-05, 'City_San Rafael'),
 (7.86121256215815e-05, 'City_MORENO VALLEY'),
 (7.336880346929502e-05, 'City_Chino Hills'),
 (7.233055079477132e-05, 'Bank_CITY NATIONAL BANK'),
 (6.705800326608419e-05, 'City_THOUSAND OAKS'),
 (6.482453342403272e-05, 'City_MANTECA'),
 (6.400576584524503e-05, 'Bank_BAY AREA EMPLOYMENT DEVEL CO'),
 (6.378517637444547e-05, 'City_SIMI (SIMI VALLEY)'),
 (6.101533007319195e-05, 'Bank_SUCCESS CAP. EXPANSION & DEVEL'),
 (5.836665171314901e-05, 'Bank_PACIFIC CITY BANK'),
 (5.5887770296640454e-05, 'Bank_SAN DIEGO PRIVATE BANK'),
 (5.2702872790542514e-05, 'City_NORTHRIDGE'),
 (5.1722479702957075e-05, 'City_ALAMEDA'),
 (4.88164853508509e-05, 'Bank_CERTIFIED DEVEL CORP OF TULARE'),
 (4.617254082279304e-05, 'City_MARYSVILLE'),
 (4.417949535954892e-05, 'City_MARINA'),
 (4.062905989006475e-05, 'Bank_READYCAP LENDING, LLC'),
 (3.967907177137711e-05, 'Bank_OPUS BANK'),
 (3.748105522144198e-05, 'City_VALLEY CENTER'),
 (3.690435023328112e-05, 'City_GRASS VALLEY'),
 (3.63335835367204e-05, 'City_LA CANADA'),
 (3.479378232408593e-05, 'City_REDWOOD CITY'),
 (3.455918693573167e-05, 'Bank_BANK OF THE WEST'),
 (3.417713168281468e-05, 'City_ROCKLIN'),
 (3.3555664320056145e-05, 'City_CAMPBELL'),
 (3.32162467566658e-05, 'Bank_U.S. BK NATL ASSOCIATION DBA P'),
 (3.244379717912464e-05, 'City_POWAY'),
 (3.083032893406953e-05, 'City_TUJUNGA'),
 (3.067548093214234e-05, 'City_RAMONA'),
 (3.063950401595057e-05, 'Bank_ZIONS FIRST NATIONAL BANK'),
 (3.063801973545216e-05, 'Bank_MISSION BANK'),
 (3.0378566674030006e-05, 'City_REDDING'),
 (2.830632315552352e-05, 'City_COVINA'),
 (2.7893380432215036e-05, 'City_PLEASANT HILL (PLEASANT HILLS)'),
 (2.6001290307098294e-05, 'City_WILMINGTON'),
 (2.5758339245912476e-05, 'City_ARCADE'),
 (2.5697136795237404e-05, 'City_TWIN PEAKS'),
 (2.3109921361425467e-05, 'City_JUNELAKE'),
 (2.3108166751803713e-05, 'Bank_MONTECITO BANK & TRUST'),
 (2.117397801442309e-05, 'City_SAN LEANDRO'),
 (2.0911937517075237e-05, 'City_COTTONWOOD'),
 (2.0774200488095287e-05, 'City_SAN FRANCSICO'),
 (1.9582783939957102e-05, 'Bank_BRIDGE BANK NATL ASSOC'),
 (1.9567253997176703e-05, 'City_PARADISE'),
 (1.902223036214772e-05, 'Bank_BANK OF THE SIERRA'),
 (1.8014927281632814e-05, 'City_VERNON'),
 (1.5539194131903554e-05, 'City_BELMONT'),
 (1.5423152003705542e-05, 'City_MIDDLETOWN'),
 (1.5125475394731534e-05, 'Bank_CALIFORNIA COASTAL CERT. DEVEL'),
 (1.3230528299794377e-05, 'City_SEBASTIANI'),
 (1.2783923612454561e-05, 'Bank_HERITAGE BANK OF COMMERCE'),
 (1.2522078244060866e-05, 'City_REDONDO BEACH'),
 (1.2285097622954003e-05, 'City_TUSTIN'),
 (1.1528891967797393e-05, 'City_EL DORADO HILLS'),
 (1.0485025871161649e-05, 'City_GROVER CITY'),
 (1.0100979374996684e-05, 'City_PISMO BEACH (PISMO)'),
 (9.703791952356037e-06, 'Bank_REDDING BANK OF COMMERCE'),
 (8.700117060990363e-06, 'City_ALISO VIEJO'),
 (8.504084499598262e-06, 'City_SAN PABLO'),
 (6.78103333508143e-06, 'City_MONTEREY'),
 (5.107881651719971e-06, 'City_EL MONTE'),
 (4.7637768415572005e-06, 'City_TWENTYNINE PALMS'),
 (4.760814615849578e-06, 'City_HAYWARD'),
 (2.810493440174265e-06, 'City_CANOGA ANNEX'),
 (1.3617049330150431e-06, 'City_LINDSAY'),
 (0.0, 'State_CA'),
 (0.0, 'City_Watsonville'),
 (0.0, 'City_WRIGHTWOOD'),
 (0.0, 'City_WINDSOR'),
 (0.0, 'City_WILLITS'),
 (0.0, 'City_WILLIAMS'),
 (0.0, 'City_WESTMINSTER'),
 (0.0, 'City_WESTLAKE VILLAGE'),
 (0.0, 'City_WEST SACRAMENTO'),
 (0.0, 'City_WEAVERVILLE'),
 (0.0, 'City_WATSONVILLE'),
 (0.0, 'City_WARNER SPRINGS'),
 (0.0, 'City_WALNUT GROVE'),
 (0.0, 'City_WALNUT CREEK'),
 (0.0, 'City_Ventura'),
 (0.0, 'City_VISTA'),
 (0.0, 'City_VICTORVILLE'),
 (0.0, 'City_VALLEY VLG'),
 (0.0, 'City_VALLEY VILLAGE'),
 (0.0, 'City_UKIAH'),
 (0.0, 'City_Temecula'),
 (0.0, 'City_TWAIN HARTE'),
 (0.0, 'City_TURLOCK'),
 (0.0, 'City_TOPANGA'),
 (0.0, 'City_TOLUCA LAKE'),
 (0.0, 'City_TEMPLE CITY (RUDELL)'),
 (0.0, 'City_TEMPLE CITY'),
 (0.0, 'City_TAHOE CITY'),
 (0.0, 'City_Sun valley'),
 (0.0, 'City_Silver Lake, CA'),
 (0.0, 'City_Santa cruz'),
 (0.0, 'City_Santa clara'),
 (0.0, 'City_San Jose'),
 (0.0, 'City_San Diego'),
 (0.0, 'City_Sacramento'),
 (0.0, 'City_SYLMAR'),
 (0.0, 'City_SUSANVILLE'),
 (0.0, 'City_SUNLAND'),
 (0.0, 'City_SPRING VALLEY'),
 (0.0, 'City_SOUTH EL MONTE'),
 (0.0, 'City_SONORA'),
 (0.0, 'City_SOMERSET'),
 (0.0, 'City_SOLANA BEACH'),
 (0.0, 'City_SIMI VALLEY'),
 (0.0, 'City_SIGNAL HILL'),
 (0.0, 'City_SHINGLE SPRINGS'),
 (0.0, 'City_SHERMAN OAKS'),
 (0.0, 'City_SHADOW HILLS'),
 (0.0, 'City_SELMA'),
 (0.0, 'City_SCOTTS VALLEY'),
 (0.0, 'City_SARATOGA'),
 (0.0, 'City_SANTEE'),
 (0.0, 'City_SANTA MARIA'),
 (0.0, 'City_SANTA FE SPRINGS'),
 (0.0, 'City_SANTA CRUZ'),
 (0.0, 'City_SANTA CLARITA'),
 (0.0, 'City_SAND CITY'),
 (0.0, 'City_SAN YSIDRO'),
 (0.0, 'City_SAN JUAN CAPISTRANO'),
 (0.0, 'City_SAN FERNANDO'),
 (0.0, 'City_SAN CARLOS'),
 (0.0, 'City_SALIDA'),
 (0.0, 'City_SAINT HELENA'),
 (0.0, 'City_SACREMENTO,'),
 (0.0, 'City_SACRAMENTP'),
 (0.0, 'City_Roseville'),
 (0.0, 'City_Riverside'),
 (0.0, 'City_Redondo Beach'),
 (0.0, 'City_Rancho Murieta'),
 (0.0, 'City_ROWLAND HEIGHTS'),
 (0.0, 'City_ROSSMOOR'),
 (0.0, 'City_ROLLING HILLS ESTATE'),
 (0.0, 'City_ROHNERT PARK'),
 (0.0, 'City_RIPON'),
 (0.0, 'City_RIO VISTA'),
 (0.0, 'City_RICHMOND'),
 (0.0, 'City_RESEDA'),
 (0.0, 'City_REEDLEY'),
 (0.0, 'City_REDWOOD SHORES'),
 (0.0, 'City_REDLANDS'),
 (0.0, 'City_RED BLUFFS'),
 (0.0, 'City_RED BLUFF'),
 (0.0, 'City_RANCHO DOMINGUEZ'),
 (0.0, 'City_RANCHO CUCAMONGA'),
 (0.0, 'City_RANCH SANTA MARGARITA'),
 (0.0, 'City_Pismo Beach'),
 (0.0, 'City_Palm Desert'),
 (0.0, 'City_PORTERVILLE'),
 (0.0, 'City_PORT HUENEME'),
 (0.0, 'City_POMONA'),
 (0.0, 'City_PLEASANT HILL'),
 (0.0, 'City_PLAYA DEL REY'),
 (0.0, 'City_PLACENTIA'),
 (0.0, 'City_PITTSBURG'),
 (0.0, 'City_PATTERSON'),
 (0.0, 'City_PASO ROBLES'),
 (0.0, 'City_PARLIER'),
 (0.0, 'City_PARAMOUNT'),
 (0.0, 'City_PALOS VERDES PENINSULA'),
 (0.0, 'City_PALOS VERDES ESTATES'),
 (0.0, 'City_PALO ALTO'),
 (0.0, 'City_PALM SPRINGS'),
 (0.0, 'City_PACIFIC PALISADES'),
 (0.0, 'City_PACIFIC MANOR'),
 (0.0, 'City_Orange'),
 (0.0, 'City_OXNARD'),
 (0.0, 'City_OROVILLE'),
 (0.0, 'City_ORANGE'),
 (0.0, 'City_OLIVEHURST'),
 (0.0, 'City_OCEANO'),
 (0.0, 'City_OAK VIEW'),
 (0.0, 'City_OAK HILLS'),
 (0.0, 'City_OAK GLEN'),
 (0.0, 'City_North Hollywood'),
 (0.0, 'City_NOVATO'),
 (0.0, 'City_NORTH HILLS'),
 (0.0, 'City_NORTH HIGHLANDS'),
 (0.0, 'City_NEWBURY PARK'),

## Analysis Questions

Finally, analyze the model's evaluation results and answer the following questions.

* **Question 1:** Would you trust in this model to deploy a loan default solution in a bank?

 * **Your answer here**


* **Question 2:** What are your insights about the top 10 most importance features?

 * **Your answer here**